// Prisma Client type extensions
import { PrismaClient } from '@prisma/client';

export type PrismaTransactionClient = Parameters<Parameters<typeof PrismaClient.prototype.$transaction>[0]>[0];

export interface PrismaClientExtended extends PrismaClient {
  // Add any custom methods or extensions here
}

// Prisma model types (these will be auto-generated by Prisma)
export type {
  User,
  Vocab,
  DictEntry,
  Example,
  Category,
  UserProgress,
  SrsCard,
  RefreshToken,
  UserDevice,
  PushNotification,
  UserDailyStats,
  UserSyncLog,
  // Add other Prisma model types as needed
} from '@prisma/client';

// Prisma include/select types
export type UserWithRelations = import('@prisma/client').User & {
  userProgress?: import('@prisma/client').UserProgress[];
  srsCards?: import('@prisma/client').SrsCard[];
  refreshTokens?: import('@prisma/client').RefreshToken[];
  devices?: import('@prisma/client').UserDevice[];
};

export type VocabWithRelations = import('@prisma/client').Vocab & {
  dictentry?: import('@prisma/client').DictEntry & {
    examples?: import('@prisma/client').Example[];
  };
  categories?: import('@prisma/client').Category[];
  userProgress?: import('@prisma/client').UserProgress[];
  srsCards?: import('@prisma/client').SrsCard[];
};

export type SrsCardWithVocab = import('@prisma/client').SrsCard & {
  vocab: import('@prisma/client').Vocab & {
    dictentry?: import('@prisma/client').DictEntry & {
      examples?: import('@prisma/client').Example[];
    };
  };
};