# .github/workflows/contract-tests.yml - Contract Testing CI/CD Pipeline
name: Contract Tests

on:
  push:
    branches: [ main, develop, GO_checklist ]
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '18'
  PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}

jobs:
  consumer-contract-tests:
    name: Consumer Contract Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        run: |
          cd web
          npm ci

      - name: Run consumer contract tests
        run: |
          cd web
          npm run test:contract:consumer
        env:
          CI: true

      - name: Upload consumer contract artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: pact-contracts
          path: web/pacts/*.json
          retention-days: 7

      - name: Publish contracts to Pact Broker
        if: github.ref == 'refs/heads/main' && env.PACT_BROKER_BASE_URL != ''
        run: |
          cd web
          npx pact-broker publish pacts --consumer-app-version=${{ github.sha }} --branch=${{ github.ref_name }}

  provider-contract-tests:
    name: Provider Contract Tests
    runs-on: ubuntu-latest
    needs: consumer-contract-tests
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
          POSTGRES_DB: language_learner_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: web/server/package-lock.json

      - name: Install server dependencies
        run: |
          cd web/server
          npm ci

      - name: Download consumer contracts
        uses: actions/download-artifact@v4
        with:
          name: pact-contracts
          path: web/pacts

      - name: Setup test database
        run: |
          cd web/server
          npm run db:test:migrate
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/language_learner_test

      - name: Run provider contract tests
        run: |
          cd web/server
          npm run test:contract:provider
        env:
          CI: true
          DATABASE_URL: postgresql://test:test@localhost:5432/language_learner_test
          REDIS_URL: redis://localhost:6379
          JWT_SECRET: test_jwt_secret
          JWT_REFRESH_SECRET: test_refresh_secret

      - name: Publish provider verification results
        if: env.PACT_BROKER_BASE_URL != ''
        run: |
          cd web/server
          # Verification results are published automatically by Pact during test execution
          echo "Provider verification results published to Pact Broker"

  can-i-deploy:
    name: Can I Deploy?
    runs-on: ubuntu-latest
    needs: [consumer-contract-tests, provider-contract-tests]
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Pact CLI
        run: npm install -g @pact-foundation/pact-node

      - name: Can I Deploy - Consumer
        if: env.PACT_BROKER_BASE_URL != ''
        run: |
          npx pact-broker can-i-deploy \
            --pacticipant Language-Learner-Client \
            --version ${{ github.sha }} \
            --to main

      - name: Can I Deploy - Provider
        if: env.PACT_BROKER_BASE_URL != ''
        run: |
          npx pact-broker can-i-deploy \
            --pacticipant Language-Learner-API \
            --version ${{ github.sha }} \
            --to main

      - name: Record deployment
        if: env.PACT_BROKER_BASE_URL != ''
        run: |
          npx pact-broker record-deployment \
            --pacticipant Language-Learner-Client \
            --version ${{ github.sha }} \
            --environment production
          
          npx pact-broker record-deployment \
            --pacticipant Language-Learner-API \
            --version ${{ github.sha }} \
            --environment production